### ISSUE TITLE
Asignacion 3.2.1

### ISSUE THREAD

**Issue by Lucia03a** [SistemasTecTlaxiaco/cursogithublucia#13]
![image](https://user-images.githubusercontent.com/89793286/131704286-e7071915-db91-4567-b01f-8a608a8156f4.png)
![image](https://user-images.githubusercontent.com/89793286/131704481-65cb4b25-75a3-48be-822f-61a864fe8aba.png)

**Comment by josealfredo79** [comment]
bien hecho y revisado
