### ISSUE TITLE
asignacion 3.4

### ISSUE THREAD

**Issue by Lucia03a** [SistemasTecTlaxiaco/cursogithublucia#15]
![image](https://user-images.githubusercontent.com/89793286/131872380-f259f8c5-24e0-499c-97ae-7954b13e9735.png)
![image](https://user-images.githubusercontent.com/89793286/131872406-0f4ae1b7-9eb1-4f54-8d7a-50c98353c773.png)

**Comment by Lucia03a** [comment]
![image](https://user-images.githubusercontent.com/89793286/131872648-7ad84814-21b6-4832-8133-07ab4c07c969.png)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
