### ISSUE TITLE
Asignación del módulo 1.2

### ISSUE THREAD

**Issue by Lucia03a** [SistemasTecTlaxiaco/cursogithublucia#2]
![image](https://user-images.githubusercontent.com/89793286/131375892-a2f0e2f0-302a-4914-af73-76d3dc8955d2.png)
![image](https://user-images.githubusercontent.com/89793286/131375941-2d54d739-24bd-4e03-b340-cbd893cc6cc2.png)

**Comment by Lucia03a** [comment]
![image](https://user-images.githubusercontent.com/89793286/131377258-c10fedf7-0feb-4b2d-8a71-34df8f4bcc29.png)

**Comment by josealfredo79** [comment]
Muy bien hecho
